<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/bootstrap.php';
require dirname(__DIR__) . '/app/producer.php';
$user = current_user();
$readOnly = $user && !studio_can($user, 'produce');
$canSettings = !$user || studio_can($user, 'settings');
$aiReady = !$readOnly && producer_allowed($user) && trim($config['openai_api_key'] ?? '') !== '';
if ($config['auth_mode'] !== 'demo' && !$user) redirect('/login.php');
$localMidi = getenv('STUDIO_LOCAL_MIDI') === '1' && in_array($_SERVER['REMOTE_ADDR'] ?? '', ['127.0.0.1','::1'], true);
$midiEnabled = ($user !== null && studio_can($user, 'settings')) || (!$user && $localMidi);
require dirname(__DIR__) . '/app/views/head.php';
?>
<link rel="stylesheet" href="/assets/ai-studio/studio.css">
<div class="shell studio-shell">
<?php $activePage = 'ai-studio'; require dirname(__DIR__) . '/app/views/sidebar.php'; ?>
<div class="workspace">
<header class="topbar"><span>Arbeidsrom <span class="slash">/</span> <strong id="studio-page-title">AI Studio</strong></span><span class="version">STUDIO <b>01</b></span><?php require dirname(__DIR__) . '/app/views/account.php'; ?></header>
<main id="main" class="ai-studio" data-settings-allowed="<?= $canSettings ? 'true':'false' ?>" data-ai-ready="<?= $aiReady ? 'true':'false' ?>" data-csrf="<?= htmlspecialchars($_SESSION['csrf'], ENT_QUOTES, 'UTF-8') ?>" data-midi-enabled="<?= $midiEnabled ? 'true':'false' ?>">
<?php if ($readOnly): ?><p class="notice">Observatør · Kun lesevisning. Lokale manus, avspilling og MIDI fra andre nettlesere deles ikke i denne versjonen.</p><fieldset disabled class="observer-view"><?php endif; ?>
<p id="feedback" role="status" class="studio-feedback">Manuell produsent klar. Velg manuell godkjenning eller automatisk kontroll av radiostikk.</p>
<div id="producer-view">
<div class="heading-row"><div><p class="eyebrow">RADIO RUBBEN / LIVE-STUDIO</p><h1>Studio <span class="dashboard-title-accent">Dashboard</span></h1><p class="intro">Din musikk. Din stemme. Full oversikt.</p></div><span class="mode"><?= $user ? escape(studio_roles()[$user['role']] ?? 'Medarbeider') : 'Producer' ?> · <?= $user ? 'Innlogget' : 'Demonstrasjon' ?></span></div>
<noscript><p class="notice">Aktiver JavaScript for Producer Board og MIDI. Radiosendingen er uavhengig av denne siden.</p></noscript>

<section class="program-header" aria-label="Program og sendestatus"><div><span class="air-status" id="air-status">ON AIR · UKJENT</span><h2 id="program-title">Velg programkontekst</h2><p id="context-source">Ingen sendekilde tilkoblet</p></div><div class="program-right"><div class="program-tools"><span id="studio-date" class="small"></span><time id="studio-clock"></time><span class="clock-zone">Norsk tid · Europe/Oslo</span><label><input id="demo-data" type="checkbox"> Vis testdata</label></div><section class="weather-widget" aria-label="Vær i studioområdet"><p id="weather-place">Bømlo · Bremnes</p><div class="weather-current"><span id="weather-icon" aria-hidden="true">–</span><div><strong id="weather-temperature">—</strong><span id="weather-condition">Henter været …</span></div></div><span id="weather-time">Lokal værprognose</span><small><a href="https://www.met.no/" target="_blank" rel="noopener">MET Norge</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a></small></section></div></section>
<div class="dashboard-grid">
<section class="track-grid" aria-label="Musikk"><article class="studio-card track"><p class="eyebrow">NÅ SPILLER</p><h2 id="now-playing">Venter på musikkdata</h2><p>Resterende tid: <span id="remaining">ukjent</span></p><div class="track-line" aria-hidden="true"></div></article><article class="studio-card track"><p class="eyebrow">NESTE LÅT</p><h2 id="next-track">Ikke tilgjengelig</h2><p>Neste låt fra musikkbiblioteket</p></article></section>
<section class="studio-card producer" aria-labelledby="producer-title"><div class="section-heading"><div><p class="eyebrow">AI PRODUSENT</p><h2 id="producer-title">Neste stikk</h2></div><span class="badge" id="producer-mode"><?= $aiReady ? 'AI klar':'Lokal mal · nøkkel mangler eller AI deaktivert' ?></span></div><p class="small">Forslag klargjøres her. Du bestemmer hva som leses på lufta.</p><details class="producer-brief"><summary>Fakta og ønsker til stikket</summary><label for="producer-notes" class="sr-only">Fakta og ønsker til stikket</label><textarea id="producer-notes" rows="3" maxlength="2000" placeholder="For eksempel: tema, bekreftet vær, lokal sak eller sponsorens godkjente tekst."></textarea><p class="small">Ved AI-generering sendes disse opplysningene, manuset og programkonteksten til OpenAI.</p></details><label for="draft" class="sr-only">Rediger manus</label><textarea id="draft" rows="7" placeholder="Skriv et stikk, eller velg Nytt stikk for å starte med en lokal mal."></textarea><div class="draft-meta"><span id="estimate">Estimert: 0 sek</span><span id="draft-origin">Manus lagres bare i denne fanen</span></div><div class="studio-actions"><button type="button" data-action="new" class="button">Nytt stikk</button><button type="button" data-action="shorter">Kortere</button><button type="button" data-action="local">Lokal sak</button><button type="button" data-action="next">Neste låt</button><button type="button" data-action="weather">Vær</button><button type="button" data-action="sponsor">Sponsor</button></div><details class="producer-options"><summary>Godkjenning, tilbakemelding og flere valg</summary><div class="studio-actions"><button type="button" id="local-template">Lag lokal mal</button><button type="button" id="undo-draft" disabled>Angre innsetting</button><button type="button" id="use-suggestion" disabled>Bruk klargjort forslag</button><label><input type="checkbox" id="auto-prepare"> Klargjør ved låtbytte</label></div><div class="studio-actions"><label for="rejection-reason">Hva bør bli bedre? (valgfritt)</label><input id="rejection-reason" type="text" maxlength="180" placeholder="For eksempel: kortere, varmere, mindre reklamespråk"><button type="button" id="reject-regenerate">Avvis og lag nytt</button></div><div class="approval-controls"><label><input type="checkbox" id="auto-review"> Kontroller og sett inn automatisk</label><p id="approval-mode" class="small">Manuell godkjenning er på.</p><p class="small">Lengde, plassholdere og en egen AI-gjennomlesing kontrolleres. Nyheter, vær og sponsorstikk går til manuell gjennomlesing. Dette er ikke ekstern faktasjekk. Kontrollen bruker et ekstra AI-kall. Sender ikke lyd på lufta.</p></div></details><pre id="suggestion-preview" hidden aria-label="Klargjort forslag"></pre><p id="suggestion-status" class="small">Automatisk klargjøring er av. Automatisk innsetting er av til du aktiverer den.</p></section>
<section class="studio-card status-card"><p class="eyebrow">STUDIO STATUS</p><h2>Kontroll på studioet</h2><dl class="studio-status"><div><dt>RØDECaster / MIDI</dt><dd id="midi-status">Disconnected</dd></div><div><dt>MIDI-utgang · valgfri</dt><dd id="output-status">Ingen valgt</dd></div><div><dt>Mikrofon · fader 1</dt><dd id="mic-status" aria-live="polite">Ukjent · venter på faderbevegelse</dd></div><div><dt>Siste MIDI-funksjon</dt><dd id="physical-status">Ingen bekreftet tilstand</dd></div><div><dt>Musikkspiller</dt><dd id="player-status">Stoppet · ingen låt lastet</dd></div><div><dt>Hue · Taklampe TV</dt><dd id="light-status">Følging av</dd></div><div><dt>Radio.co / BUTT</dt><dd>Sendestatus ukjent · ingen overvåking tilkoblet</dd></div><div><dt>AI</dt><dd id="ai-status"><?= $aiReady ? 'Klar · ikke testet':'Ikke konfigurert · manuell drift' ?></dd></div><div><dt>Studioserver</dt><dd id="site-status">Kontrollerer forbindelse …</dd></div></dl><p class="small">MIDI viser kontrollsignaler. Det bekrefter ikke at mikrofonen er på lufta.</p></section>
<section class="studio-card log-card"><div class="section-heading"><div><p class="eyebrow">SENDELOGG</p><h2>I studio nå</h2></div></div><ol id="studio-log" class="studio-log" aria-label="Siste studiohendelser"></ol><div class="studio-actions"><button id="export-log" type="button">Last ned logg</button><button id="clear-log" type="button">Tøm logg</button></div><p class="small">Inntil 500 hendelser i minnet. Ingen lyd eller manustekst lagres i loggen.</p></section>
<section class="studio-card pads-card"><p class="eyebrow">SMART PADS</p><h2>Produsentens snarveier</h2><div id="pad-board" class="pad-board"></div><p class="small">Skjermknappene virker også uten MIDI. Aktiver fysisk mapping under Innstillinger.</p></section>
<section class="studio-card music-library" aria-labelledby="music-title"><p class="eyebrow">MUSIKKBIBLIOTEK / LOKAL AVSPILLING</p><h2 id="music-title">Velg neste låt</h2><p class="small">AI får artist, tittel og album fra mappen, aldri lydfilene. AI velger etter norsk ukedag, tid og stemning. Du starter første låt. Automatikk kan deretter fortsette avspillingen.</p><div class="studio-actions"><button type="button" id="music-load">Les musikkmappen</button><button type="button" id="music-output">Velg lydutgang</button></div><label><input type="checkbox" id="music-output-confirmed"> Lydutgangen er satt til RØDECaster</label><p id="music-mood" class="small">Henter dagens musikkstemning …</p><div class="port-grid"><label>Overstyr stemning (valgfritt)<input id="music-wish" type="text" maxlength="400" placeholder="La stå tomt for dagens stemning"></label><label>Neste låt<select id="music-selection"><option value="">Les musikkmappen først</option></select></label></div><div class="studio-actions"><button type="button" id="music-ai" disabled>AI: Velg neste låt</button><button type="button" id="music-play" disabled>Spill neste</button><button type="button" id="music-stop">Stopp musikk</button><button type="button" id="music-clear-history">Tøm spillehistorikk</button></div><div class="studio-actions"><label><input type="checkbox" id="music-auto-pick"> AI klargjør neste låt automatisk</label><label><input type="checkbox" id="music-auto-play"> Spill videre automatisk</label><label>Stikk etter<select id="music-break-interval"><option value="1">Hver låt</option><option value="3" selected>Tre låter</option><option value="5">Fem låter</option></select></label></div><p id="music-break-status" class="small">Stikkmappe er ikke lest.</p><p class="small">Stopp musikk slår av automatikk. Ved AI-feil velges neste tilgjengelige låt lokalt. Avspilling krever at denne fanen og Macen er våkne.</p><audio id="music-audio" preload="metadata"></audio><p id="music-status" role="status" class="small">Biblioteket er ikke lest ennå. Ingen automatisk avspilling.</p></section>
</div>
</div>
<div id="settings-view" hidden>
<div class="heading-row"><div><p class="eyebrow">RADIO RUBBEN / STUDIO</p><h1>Innstillinger</h1><p class="intro">Tilkoblinger, MIDI-monitor og SMART Pads.</p></div></div>
<section class="studio-card"><p class="eyebrow">AI PRODUSENT / TILBAKEMELDINGER</p><h2>Rubbens stil</h2><p>De tre siste avvisningene huskes i denne nettleseren og følger med ved neste AI-generering. Dette gir modellen stilføringer; det trener ikke selve modellen. Avviste utdrag brukes ikke som fakta.</p><p id="feedback-memory-status" class="small"></p><ul id="feedback-memory"></ul><button id="forget-feedback" type="button">Slett huskede tilbakemeldinger</button></section><section id="settings" class="studio-card settings"><p class="eyebrow">INNSTILLINGER / RØDECASTER</p><h2>USB MIDI og SMART Pads</h2><p>Åpne denne siden på maskinen som er koblet til RØDECaster med USB. Gi nettleseren MIDI-tilgang og velg inngang.</p>
<?php if (!$midiEnabled): ?><p class="notice">Offentlig demonstrasjon: MIDI er deaktivert. Lokal testing krever STUDIO_LOCAL_MIDI=1; på nettstedet kreves innlogging.</p><?php endif; ?>
<div class="studio-actions"><button type="button" id="connect-midi" <?= !$midiEnabled ? 'disabled':'' ?>>Finn MIDI-enheter</button><button type="button" id="disconnect-midi" disabled>Koble fra</button></div>
<div class="port-grid"><label>MIDI Input<select id="midi-input" disabled><option value="">Ingen valgt</option></select></label><label>MIDI Output (valgfri)<select id="midi-output" disabled><option value="">Ingen valgt</option></select></label></div><label><input type="checkbox" id="rode-confirm" disabled> Valgt inngang tilhører RØDECaster Pro II – tolk dokumenterte kontrollsignaler</label><p class="small">Ingen MIDI-kommandoer sendes til utstyret i fase 1. Generiske portnavn må velges manuelt.</p>
<h3>Philips Hue</h3><label><input type="checkbox" id="hue-follow"> La Taklampe TV følge MIC LIVE</label><p id="hue-status" role="status" class="small">Av · Taklampe TV: rødt ved fader opp, tidligere lys ved fader ned.</p><p class="small">MIC LIVE styrer bare valgte studiolamper. Pad-handlingen «Slå av alle Hue-lys» sender avslåing til hele Hue-broen og pauser lysfølging til du slår den på igjen. Utilgjengelige lamper kan ikke bekreftes avslått. Den lokale Hue-vakten gjenoppretter lyset hvis Studio slutter å svare. Krever at denne Macen kjører og når bridgen.</p><h3>MIC LIVE fra fader 1</h3><p>Indikatoren øverst følger faderens posisjon. Den bekrefter ikke mute, lydruting eller at sendingen er på lufta. Kalibrer bare fader 1, og la andre MIDI-kontroller stå stille.</p><div class="studio-actions"><button id="learn-mic-fader" type="button">Lær fader 1</button><button id="cancel-mic-fader" type="button" disabled>Avbryt faderinnlæring</button></div><p id="mic-fader-status" role="status" class="small">Ikke konfigurert. Koble til MIDI og lær nedre og øvre posisjon.</p><h3>MIDI Monitor</h3><p id="last-midi" class="small">Siste event: ingen</p><div class="studio-actions"><button id="monitor-toggle" type="button">Stop Monitor</button><button id="monitor-clear" type="button">Clear</button><button id="monitor-copy" type="button">Copy Log</button><span id="monitor-status">Monitor kjører · 0 events</span></div><div class="table-scroll"><table><thead><tr><th>Timestamp</th><th>Channel</th><th>Type</th><th>CC / note</th><th>Value</th><th>Tolket funksjon</th></tr></thead><tbody id="midi-rows"></tbody></table></div><p class="small">Maks 300 events. Stop Monitor pauser bare visningen; pad-handlinger fortsetter.</p>
<h3>SMART Pad mapping</h3><p class="small">Velg «Lær», trykk én pad og kontroller kanal/type/verdi. Aktiver deretter raden og lagre. Standardnumrene er eksempler, ikke RØDE-fabrikkmapping. CC med verdi 0 kan være slipp: velg bevisst hvilken kant som skal utløse handlingen.</p><div class="table-scroll"><table><thead><tr><th>Aktiv / Pad</th><th>Kanal</th><th>Type</th><th>CC / note</th><th>Verdi</th><th>Handling</th><th>Innlæring</th></tr></thead><tbody id="mapping-rows"></tbody></table></div><div class="studio-actions"><button id="save-mapping" type="button" class="button">Lagre mapping</button><button id="cancel-learn" type="button" disabled>Avbryt innlæring</button></div><p id="mapping-status" role="status" class="small">Mapping lagres lokalt i denne nettleseren. Alle pads er deaktivert til du aktiverer dem.</p>
</section>
</div>
<?php if ($readOnly): ?></fieldset><?php endif; ?><footer><span>Radio Rubben <b>AI Studio</b></span><span>Radiosendingen fungerer uavhengig av AI Studio.</span></footer>
</main></div></div><?php if (!$readOnly): ?><script type="module" src="/assets/ai-studio/app.mjs?v=roles-1"></script><?php endif; ?></body></html>
