<?php
$audioConfig=$config['rr_audio']??[];$audioBoard=studio_board_read();
?>
<section class="control-panel" id="audio-material"><h2>RR Audio</h2>
<p>Selvstendige radiomanus fra sakens kontrollerte originalgrunnlag. KI-generert stemme krever egen gjennomlytting og sluttgodkjenning.</p>
<?php if(empty($audioConfig['enabled'])):?><p>Talegenerering er deaktivert. Manus og uttaleordbok kan klargjøres.</p><?php endif;?>
<?php if($can):?><form method="post" class="editor-form"><?php case_fields($item);?><label>Manusprofil<select name="profile"><?php foreach(rr_audio_profiles()as$key=>$p):?><option value="<?=escape($key)?>"><?=escape($p['name'])?></option><?php endforeach;?></select></label><button name="action" value="audio_generate_script">Lag separat radiomanus</button></form><?php endif;?>
<?php foreach($item['audioScripts']??[]as$key=>$v):$a=$v['audio']??[];$p=rr_audio_profile($key);?>
<details open><summary><?=escape($p['name'])?></summary>
<?php if(isset($a['raw'])&&!rr_audio_current($item,$v,$audioBoard,$audioConfig)):?><p>Utdatert lyd: ny kontroll, godkjenning og generering kreves før sending.</p><?php endif;?>
<p>Manus: <?=rr_audio_script_approved($item,$v)?'Sluttgodkjent':(rr_audio_checked($item,$v)?'Venter på godkjenning':'Trenger kontroll')?>. Lyd: <?=escape(['generating'=>'Genereres','needs_processing'=>'Klar for lydbehandling','processed'=>'Behandlet – kontroller godkjenning','failed'=>'Forespørsel avvist','unknown'=>'Uavklart forespørsel','resolved'=>'Avklart – kan forsøkes på nytt','stale'=>'Utdatert'][$a['status']??'']??'Ikke generert')?>.</p>
<?php if($can):?><form method="post" class="editor-form"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><label>Radiomanus<textarea name="script" rows="6" maxlength="2200" required><?=escape($v['script'])?></textarea></label><button name="action" value="audio_save">Lagre manusendring</button></form>
<form method="post"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><button name="action" value="audio_check">Kildekontroller lagret manus</button></form>
<?php else:?><p><?=nl2br(escape($v['script']))?></p><?php endif;?>
<?php case_report($v['check']??[]);?>
<?php if($can&&rr_audio_checked($item,$v)):?><form method="post"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><label><input type="checkbox" name="confirmed" value="1" required> Jeg har lest og kontrollert dette manuset</label><button name="action" value="audio_approve_script">Sluttgodkjenn manus</button></form><?php endif;?>
<?php if($can&&rr_audio_script_approved($item,$v)&&!empty($audioConfig['enabled'])):?><form method="post" class="editor-form"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><label>Godkjent stemme<select name="voice" required><?php foreach($audioConfig['voices']??[]as$voice=>$vp):try{rr_audio_voice($audioConfig,$voice,(string)($item['program']??''));}catch(Throwable){continue;}?><option value="<?=escape($voice)?>"><?=escape($vp['label'])?></option><?php endforeach;?></select></label><label>Talehastighet<input type="number" name="speed" min="0.8" max="1.2" step="0.05" value="1"></label><label>Uttrykk<input type="number" name="style" min="0" max="1" step="0.1" value="0"></label><p>Generering bruker ElevenLabs-kvoten. Ny lyd må godkjennes på nytt.</p><button name="action" value="audio_tts">Generer lyd</button></form><?php endif;?>
<?php if(isset($a['raw'])):?><p><?=isset($a['master'])?'Behandlet lyd':'Ubehandlet forhåndslytting'?></p><audio controls preload="none" src="/audio-file.php?item=<?=escape($item['id'])?>&amp;profile=<?=escape($key)?>&amp;kind=<?=isset($a['master'])?'master':'raw'?>"></audio><?php endif;?>
<?php foreach($a['qa']['issues']??[]as$issue):?><p><?=escape($issue)?></p><?php endforeach;?>
<?php if(isset($a['measurements'])):?><p>Varighet: <?=number_format($a['measurements']['duration'],1,',','')?> sekunder.</p><?php endif;?>
<?php if($can&&isset($a['raw'])&&rr_audio_current($item,$v,$audioBoard,$audioConfig)):?><form method="post"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><button name="action" value="audio_process">Behandle og kontroller lyd</button><p>Bruker lagret lyd uten ny TTS-kostnad.</p></form><?php endif;?>
<?php if($can&&!empty($a['qa']['passed'])&&rr_audio_current($item,$v,$audioBoard,$audioConfig)):?><form method="post"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><label><input type="checkbox" name="confirmed" value="1" required> Jeg har lyttet gjennom lyden og kontrollert innhold, uttale og lydkvalitet</label><button name="action" value="audio_approve_audio">Sluttgodkjenn lyd</button></form><?php endif;?>
<?php if(rr_audio_ready($item,$v,$audioBoard,$audioConfig)):?><p>Lyd sluttgodkjent.</p><?php if($can):?><form method="post"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><button name="action" value="audio_enqueue">Legg godkjent lyd i sendelisten</button></form><?php endif;endif;?>
<?php if($admin&&in_array($a['status']??'', ['unknown','generating'],true)):?><form method="post" class="editor-form"><?php case_fields($item);?><input type="hidden" name="profile" value="<?=escape($key)?>"><label>Resultat av kontroll i ElevenLabs<input name="resolution" minlength="10" maxlength="500" required></label><label><input type="checkbox" name="confirmed" value="1" required> Jeg har avklart forespørselen og eventuell belastning hos leverandøren</label><button name="action" value="audio_resolve">Registrer avklaring</button></form><?php endif;?></details>
<?php endforeach;?>
<details><summary>Uttaleordbok · versjon <?=(int)rr_pronunciation_context($audioBoard)['version']?></summary><p>Uttaler må foreslås og godkjennes manuelt. En aktiv endring krever ny lyd og gjennomlytting.</p>
<?php foreach(($audioBoard['pronunciation']??rr_pronunciation_seed())['entries']as$e):?><p><?=escape($e['term'])?> → <?=escape($e['alias']?:'Ikke avklart')?> · <?=escape(['unverified'=>'Uavklart','pending'=>'Til godkjenning','approved'=>'Godkjent','disabled'=>'Deaktivert','rejected'=>'Avvist'][$e['status']]??$e['status'])?></p>
<?php if($admin&&in_array($e['status'],['pending','approved'],true)):?><form method="post"><?php case_fields($item);?><input type="hidden" name="entry" value="<?=escape($e['id'])?>"><input type="hidden" name="entry_revision" value="<?=(int)$e['revision']?>"><?php if($e['status']==='pending'):?><label><input type="checkbox" name="confirmed" value="1" required> Jeg bekrefter den lokale uttalen</label><button name="action" value="pronunciation_approve">Godkjenn uttale</button><?php else:?><button name="action" value="pronunciation_disable">Deaktiver uttale</button><?php endif;?></form><?php endif;endforeach;?>
<?php if($can):?><form method="post" class="editor-form"><?php case_fields($item);?><label>Navn<input name="term" maxlength="100" required></label><label>Uttalemåte<input name="alias" maxlength="100" required></label><button name="action" value="pronunciation_propose">Foreslå uttale</button></form><?php endif;?></details></section>
