<main id="main" class="newsroom" data-selected="<?=escape($selected)?>">
<header class="nr-heading"><div><h1>Nyhetsdesk</h1><p><?=$counts['ready']?> saker klare til godkjenning</p></div><a class="nr-refresh" data-newsroom-link href="<?=escape(studio_newsroom_url($selected,$filter))?>">Oppdater</a></header>
<?php if($error):?><p class="nr-alert" role="alert"><?=escape($error)?></p><?php endif;?>
<?php if($notice):?><p class="nr-notice" role="status"><?=escape($notice)?></p><?php endif;?>
<?php if($wpError):?><p class="nr-alert">WordPress: <?=escape($wpError)?> <a href="/wordpress-check.php">Se tilkoblingskontroll</a></p><?php endif;?>
<div class="nr-layout"><details class="nr-queue" id="nr-queue"><summary>Velg sak <span><?=$counts['ready']?> klare · <?=count($cards)?> totalt</span></summary><nav class="nr-counts" aria-label="Filtrer saker"><a data-newsroom-link href="/newsdesk.php?filter=all" <?=$filter==='all'?'aria-current="page"':''?>><strong><?=count($cards)?></strong>Alle saker</a><?php foreach($labels as $key=>$label):?><a data-newsroom-link href="/newsdesk.php?filter=<?=$key?>" <?=$filter===$key?'aria-current="page"':''?>><strong><?=$counts[$key]?></strong><?=escape($label)?></a><?php endforeach;?></nav>
<?php if(!$visible):?><p class="nr-empty">Ingen saker i denne gruppen. Nye utkast vises her når de er klargjort.</p><?php endif;?>
<?php foreach($visible as $key=>$row):?><a class="nr-card <?=$key===$selected?'selected':''?>" data-newsroom-link href="/newsdesk.php?filter=<?=escape($filter)?>&amp;item=<?=rawurlencode($key)?>"><span class="nr-badge <?=escape($row['status'])?>"><?=escape($labels[$row['status']]??'Utkast')?></span><h3><?=escape($row['title'])?></h3><?php if(isset($row['flow'])):?><p>Radio: <?=escape($row['flow']['radio'])?><br>Nett: <?=escape($row['flow']['web'])?></p><?php endif;?><p><?=escape($row['sourceName']??'Fotball')?></p><?php if($row['reasons']??[]):?><small><?=escape($row['reasons'][0])?></small><?php endif;?></a><?php endforeach;?></details>
<section class="nr-reader" aria-label="Les og godkjenn saken"><div id="nr-reader-start" tabindex="-1"></div>
<?php if($card):?><nav class="nr-reader-nav" aria-label="Bytt sak"><button type="button" data-open-queue>Velg sak</button><span><?=$position!==false?$position+1:1?> av <?=max(1,count($visible))?></span><?php if($nextKey):?><a data-newsroom-link href="<?=escape(studio_newsroom_url($nextKey,$filter))?>">Neste sak →</a><?php endif;?></nav><?php endif;?>
<?php if(!$card):?><div class="nr-empty"><h2>Du er ajour med denne køen</h2><p>Velg en annen gruppe under «Velg sak», eller se innkomne forslag nedenfor.</p></div><?php else:?>
<span class="nr-badge <?=escape($card['status'])?>"><?=escape($labels[$card['status']]??'Utkast')?></span><h2 class="nr-title"><?=escape($card['title'])?></h2>
<p class="nr-meta"><?=escape($card['sourceName']??'Fotballroboten')?><?php if(!empty($card['sourceUrl'])):?> · <a href="<?=escape($card['sourceUrl'])?>" target="_blank" rel="noopener noreferrer">Les originalen ↗</a><?php endif;?></p>
<?php $canReject=$can&&$card['status']!=='published'&&($item||($admin&&!$wpError)); ?>
<?php if($canReject):?><div class="nr-reject-shortcut"><button type="button" data-open-reject class="nr-reject-button"><?=!empty($card['isCorrection'])?'Forkast endringsforslag':'Forkast forslag'?></button><small>Fjerner forslaget fra arbeidskøen. Historikken beholdes.</small></div><?php endif;?>
<?php if($canReject):?><details id="nr-rejection"><summary>Begrunn forkasting</summary><form id="nr-reject-form" method="post" data-newsroom><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="reject"><label>Hvorfor forkastes saken?<textarea name="comment" minlength="10" maxlength="1000" rows="3" required placeholder="For eksempel: Allerede omtalt, utdatert, svakt kildegrunnlag eller ikke relevant for Bømlo."></textarea></label><p>Begrunnelsen lagres med saken. For Studio-saker brukes den som et redaksjonelt eksempel ved senere utvalg i samme program, aldri som en automatisk fast regel.</p><button>Bekreft forkasting</button></form></details><?php endif;?>
<?php if($item): $relevance=$item['relevance']??null; require __DIR__.'/news-relevance.php'; endif;?>
<?php if($item): $flow=$card['flow']??studio_newsroom_flow($item); ?>
<section class="nr-channel-flow" aria-label="Kanalstatus og neste handling">
<h3>Én sak · <?=escape(['radio'=>'Radio','web'=>'Nett','both'=>'Radio og nett'][$flow['channel']])?></h3>
<dl><div><dt>Radio</dt><dd><?=escape($flow['radio'])?></dd></div><div><dt>Nett</dt><dd><?=escape($flow['web'])?></dd></div></dl>
<p><a class="nr-primary" href="<?=escape($flow['next']['url'])?>"><?=escape($can?$flow['next']['label']:'Åpne saken')?></a></p>
<p><a href="/case.php?item=<?=escape($item['id'])?>">Endre kanalvalg og se hele saken</a></p>
<?php if($flow['channel']!=='web'):?><small>Manusgodkjenning er ikke lydgodkjenning. Lyd vurderes separat.</small><?php endif;?>
</section>
<?php endif;?>
<?php if($item&&studio_board_channel($item)==='radio'):?>
<h3>Radiomanus</h3><article class="nr-prose"><?=nl2br(escape($item['script']?:'Radiomanuset er ikke laget ennå.'))?></article>

<?php else:?>
<?php if($item):?><figure class="nr-image"><img src="/assets/radio-rubben-nyheter.png" alt="Radio Rubben Nyheter" width="1024" height="576"><figcaption>Radio Rubbens KI-genererte illustrasjon.</figcaption></figure><?php elseif(!empty($card['image']['previewUrl'])):?><figure class="nr-image"><img src="<?=escape($card['image']['previewUrl'])?>" alt="<?=escape($card['image']['alt']??'Artikkelens hovedbilde')?>" loading="lazy"><figcaption><?=escape($card['image']['caption']??'')?></figcaption></figure><?php else:?><p class="nr-image-warning">Bilde mangler i forhåndsvisningen.</p><?php endif;?>
<?php if(!empty($card['notice'])):?><p class="nr-ai-notice"><?=escape($card['notice'])?></p><?php endif;?>
<?php if($item && parse_url($item['sourceUrl'],PHP_URL_HOST)==='www.nrk.no'):?><p class="nr-source">Basert på opplysninger fra NRK. <a href="<?=escape($item['sourceUrl'])?>" target="_blank" rel="noopener noreferrer">Les hele saken hos NRK ↗</a></p><?php endif;?>
<article class="nr-prose"><p class="nr-intro"><?=escape($card['intro']??'')?></p><?php foreach(studio_news_reading_paragraphs($card['body']??'') as $paragraph):?><p><?=escape($paragraph)?></p><?php endforeach;?></article>
<?php if($card['links']??[]):?><details class="nr-links"><summary>Kilder til saken</summary><?php foreach($card['links'] as $link):?><p><a href="<?=escape($link['url'])?>" target="_blank" rel="noopener noreferrer"><?=escape($link['label'])?></a></p><?php endforeach;?></details><?php endif;?>
<?php if($item&&$card['originalRead']):?><p class="nr-source">Originalartikkelen er lest · <?=escape(newsroom_time($card['sourceFetchedAt']))?>. <?php if(parse_url($item['sourceUrl'],PHP_URL_HOST)==='www.nrk.no'):?><a href="<?=escape($item['sourceUrl'])?>" target="_blank" rel="noopener noreferrer">Les hele saken hos NRK ↗</a><?php endif;?></p><?php endif;?>
<?php if($card['reasons']??[]):?><section class="nr-blockers"><h3><?=$card['status']==='ready'?'Ved godkjenning':'Dette gjenstår'?></h3><ul><?php foreach($card['reasons'] as $reason):?><li><?=escape($reason)?></li><?php endforeach;?></ul></section><?php endif;?>
<?php if($card['status']==='published'&&!empty($card['publishedUrl'])):?><p><a class="nr-primary" href="<?=escape($card['publishedUrl'])?>" target="_blank" rel="noopener noreferrer">Åpne saken på nett ↗</a></p>
<?php elseif($can):?><div class="nr-decisions">
<?php if(($admin&&!empty($card['canApprove'])&&!$wpError)||$item||!empty($card['canRevise'])||$canReject):?><div class="nr-dock">
<?php if($admin&&!empty($card['canApprove'])&&!$wpError):?><form method="post" data-newsroom class="nr-approve"><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="approve"><label class="nr-confirm"><input type="checkbox" name="confirmed" value="1" required> Jeg har lest saken</label><div class="nr-dock-buttons"><?php if($item||!empty($card['canRevise'])):?><button type="button" class="nr-change-button" data-open-changes>Endre</button><?php endif;?><button class="nr-primary"><?=!empty($card['isCorrection'])?'Godkjenn og oppdater':'Godkjenn og publiser'?></button></div></form>
<?php elseif($item||!empty($card['canRevise'])):?><button type="button" data-open-changes>Be om endringer</button><?php endif;?>
<?php if($canReject):?><button type="button" data-open-reject class="nr-reject-button"><?=!empty($card['isCorrection'])?'Forkast endringsforslag':'Forkast forslag'?></button><?php endif;?>
</div><?php endif;?>
<?php if($item||!empty($card['canRevise'])):?><details id="nr-changes"><summary>Be om endringer</summary><form method="post" data-newsroom><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="revise"><label>Hva ønsker du endret?<textarea name="comment" maxlength="2000" rows="3" required placeholder="For eksempel: Gjør ingressen kortere og vinklingen mer lokal."></textarea></label><?php if(!$item&&($card['canAddFacts']??true)):?><label>Egne opplysninger du står som kilde til<textarea name="editorial_facts" rows="2" maxlength="2000"></textarea></label><?php endif;?><button>Bearbeid og vis ny tekst her</button></form></details><?php endif;?>

<?php if($item&&$card['status']==='attention'):?><form method="post" data-newsroom><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="<?=empty($card['body'])?'prepare':'check'?>"><button><?=empty($card['body'])?'Hent original og klargjør':'Kontroller lagret tekst på nytt'?></button></form><?php endif;?></div>
<?php if($item):?><details class="nr-edit"><summary>Rediger teksten selv</summary><form method="post" data-newsroom><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="save"><label>Overskrift<input name="title" maxlength="180" value="<?=escape($card['title'])?>" required></label><label>Ingress<textarea name="intro" maxlength="500" required><?=escape($card['intro'])?></textarea></label><label>Artikkeltekst<textarea name="body" rows="12" maxlength="5000" required><?=escape($card['body'])?></textarea></label><label>Plassering<select name="news_scope"><option value="news">Nyheter</option><option value="local" <?=($item['web']['publication']['scope']??'')==='local'?'selected':''?>>Nyheter og Lokale Nyheter</option></select></label><button>Lagre og kontroller</button></form></details><?php endif;?>
<?php endif;?>
<?php endif;?>
<?php if($item&&$can&&($item['program']??'')==='god-morgen-vestland'):?>
<details class="nr-feedback"><summary>Kommentar til Robåten</summary>
<p>Beskriv en språkfeil eller hvor teksten går lenger enn kilden. Kommentaren lagres med denne tekstversjonen og kildegrunnlaget.</p>
<form method="post" data-newsroom><?php newsroom_fields($selected,$card);?><input type="hidden" name="action" value="feedback">
<label>Hva skal Robåten gjøre bedre?<textarea name="comment" rows="3" minlength="10" maxlength="500" required placeholder="Kilden sier smerter, ikke alvorlig skade. Bevar kildens skadegrad og forbehold."></textarea></label>
<?php if($admin):?><label><input type="checkbox" name="apply" value="1"> Bruk kommentaren som skriveråd i nye nett- og radioutkast for God morgen Vestland</label>
<label><input type="checkbox" name="styleOnly" value="1"> Skriverådet gjelder språk og kildebruk, aldri nye fakta eller unntak fra kontroll</label><?php endif;?>
<p>Lagrede utkast endres ikke. Kommentaren er ikke en ny faktakilde.</p><button>Lagre kommentar</button>
</form>
<?php $caseFeedback=array_values(array_filter($board['editorialRules']??[],static fn($rule)=>($rule['evidence']['kind']??'')==='feedback'&&($rule['evidence']['itemId']??'')===$item['id']));?>
<?php if($caseFeedback):?><h3>Tidligere kommentarer</h3><?php foreach(array_reverse($caseFeedback) as $feedback):?><p><?=escape($feedback['text'])?><br><small><?=escape($feedback['createdBy'])?> · tekstversjon <?=(int)$feedback['evidence']['revision']?> · <?=escape(['approved'=>'Aktivt skriveråd','pending'=>'Venter på godkjenning','disabled'=>'Deaktivert','rejected'=>'Avvist'][$feedback['status']]??'Lagret')?></small></p><?php endforeach;?><?php endif;?>
<p><a href="/learning.php?view=pending">Se og administrer læringen</a></p>
</details>
<?php endif;?>
<?php if($item): $evidence=studio_board_channel($item)==='radio'?($item['sourceCheck']??[]):($item['web']['check']??[]);?><details class="nr-evidence"><summary>Kilder og kontroll</summary><?php if(!empty($item['web']['generation']['stylebookVersion'])):?><p>Utarbeidet med KI-støtte etter Radio Rubben Stylebook <?=escape($item['web']['generation']['stylebookVersion'])?>. Redaksjonen må lese teksten og kontrollrapporten før godkjenning.</p><?php endif;?><p>Kildekontroll: <?=escape(newsroom_time($card['checkedAt']))?></p><?php if(!empty($evidence['source']['text'])):?><p><?=nl2br(escape($evidence['source']['text']))?></p><?php endif;?><a href="/case.php?item=<?=escape($item['id'])?>">Radiomanus og full sakshistorikk</a></details><?php endif;?>
<?php endif;?></section></div>

<details class="nr-inbox"><summary>Innkommet fra NRK Vestland og Bømlo kommune · <?=count($sources)?> kildesaker</summary><p>Kildepekere beholdes inntil 30 dager, slik at kommende lokale aktiviteter kan vurderes. Publiseringstid alene avgjør ikke aktualitet. Saker som er tatt inn til behandling, manus og historikk beholdes.</p><div class="nr-source-grid">
<?php foreach($sources as $source): $selection=$board['newsSelections'][studio_source_identity($source['url'])]['assessment']??null;?><article>
<?php if($selection):?><p><strong><?=escape(studio_relevance_labels()[$selection['recommendation']]??'Venter')?></strong>: <?=escape($selection['reason'])?></p><p>Radio: <?=escape($selection['radioReason'])?><br>Nett: <?=escape($selection['webReason'])?></p>
<details><summary>Belegg og tidspunkt</summary><p>Hendelsesdato: <?=escape($selection['eventDate']??'Ukjent')?></p>
<?php foreach($selection['localEvidence']??[] as $quote):?><blockquote><?=escape($quote)?></blockquote><?php endforeach;?>
<?php if(!empty($selection['relatedId'])):?><p><a href="/case.php?item=<?=rawurlencode($selection['relatedId'])?>">Tidligere sak</a> · <?=escape($selection['relationReason']??'')?></p><?php endif;?>
</details><?php endif;?><p class="nr-meta"><?=escape($source['sourceName'])?> · <?=escape(newsroom_time($source['publishedAt']))?></p><h3><?=escape($source['title'])?></h3><p><?=escape($source['summary'])?></p><a href="<?=escape($source['url'])?>" target="_blank" rel="noopener noreferrer">Åpne originalen ↗</a><?php if($can):?><form method="post" data-newsroom><input type="hidden" name="csrf" value="<?=escape($_SESSION['csrf'])?>"><input type="hidden" name="source" value="<?=escape($source['id'])?>"><input type="hidden" name="action" value="open_source"><?php if(!studio_board_has_source($board['items'],$source)):?><label>Bruk saken til<select name="channel"><option value="both">Radio og nett</option><option value="radio">Radio</option><option value="web">Nett</option></select></label><?php endif;?><button><?=studio_board_has_source($board['items'],$source)?'Se eksisterende sak':'Hent original og vurder'?></button></form><?php endif;?></article><?php endforeach;?></div></details>
<details class="nr-settings"><summary>Automatikk og samlevarsler</summary><p>Automatisk klargjøring: <strong><?=$settings['enabled']?'På':'Pause'?></strong>. Inntil åtte nye saker per døgn. Originalen leses før skriving; du godkjenner publisering.</p><p>E-post samler nye, ferdige saker i ett varsel med lenke hit. Ingen artikkeltekst sendes i varselet. Uendrede saker gir ikke nye e-poster.</p><?php if(!empty($wpStatus['notification']['message'])):?><p><?=escape($wpStatus['notification']['message'])?></p><?php endif;?>
<?php if($admin):?><form method="post" data-newsroom><input type="hidden" name="csrf" value="<?=escape($_SESSION['csrf'])?>"><input type="hidden" name="action" value="settings"><input type="hidden" name="enabled" value="<?=$settings['enabled']?'0':'1'?>"><button><?=$settings['enabled']?'Sett klargjøring på pause':'Start automatisk klargjøring'?></button></form><?php endif;?><p><a href="/sending.php">Åpne sendelisten</a> · <a href="/control.php">Trafikk, vær og kontrollsenter</a></p></details>
</main>
